version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    allow:
      - dependency-type: "direct"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
