on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: Release stable or canary?
        required: true
        type: choice
        options:
          - canary
          - stable
      semverType:
        description: semver type?
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  id-token: write

name: Release

env:
  SEMVER_TYPE: ${{ github.event.inputs.semverType }}
  RELEASE_TYPE: ${{ github.event.inputs.releaseType }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v6
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Configure git
      run: |
        git config user.name "dragate"
        git config user.email "spidfair@gmail.com"
    - name: Bump version and tag
      id: bump
      run: node ./scripts/bump-version.js
    - name: Push version commit
      run: |
        git push origin ${GITHUB_REF#refs/heads/}
        git push origin --tags
    - name: Create release
      run: gh release create v${{ steps.bump.outputs.version }} --target ${GITHUB_REF#refs/heads/} --generate-notes ${{ github.event.inputs.releaseType == 'canary' && '--prerelease' || '' }}
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Publish package
      run: pnpm publish --no-git-checks --access public --tag ${{ github.event.inputs.releaseType }}