on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: Release stable or canary?
        required: true
        type: choice
        options:
          - canary
          - stable

      semverType:
        description: semver type?
        type: choice
        options:
          - patch
          - minor
          - major

    secrets:
      RELEASE_BOT_GITHUB_TOKEN:
        required: true

name: Release

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Publish package
        run: npm Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}